### PR TITLE
Increased testing coverage to above 90%

### PR DESCRIPTION
**Pull request by Rautherdir**
I did add a few more developer dependencies, Unexpected and Unexpected-EventEmitter were added as an easier-to-use alternative to assert; process-void was something I made to make running some of the tests easier.

This also fixed some typos in the documentation, as well as fixing the implementation of Error Limit Listeners.

### CODE REVIEW

**Comment by Cherry** [comment]
Fantastic PR, thanks! 👍

It appears that the `allows the process to exit gracefully` test is currently failing, but if you can resolve that one, we'll get this merged ASAP.

**Comment by Rautherdir** [comment]
Oh... I made my dates regex wrong. Fixing that.

**Comment by Rautherdir** [comment]
Hmm, let me see if I can fix that.

**Comment by Cherry** [comment]
Fantastic, thanks very much. I'm going to squash and merge to avoid polluting the commit tree, and will then push a new release.

**Pull request merged**
